# Generated by Django 5.2.17 on 2026-08-16 18:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeOfWork',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('code', models.CharField(help_text='Stable reference, for example SCI-Y8-S1.', max_length=48)),
                ('description', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schemes_of_work', to='schools.academicyear')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_schemes', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes_of_work', to='schools.school')),
                ('school_class', models.ForeignKey(help_text='The level or year group this scheme sequences.', on_delete=django.db.models.deletion.PROTECT, related_name='schemes_of_work', to='schools.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schemes_of_work', to='schools.subject')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='curriculum.schemeofwork')),
                ('term', models.ForeignKey(blank=True, help_text='Leave empty for a whole-year scheme.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schemes_of_work', to='schools.term')),
            ],
            options={
                'verbose_name': 'scheme of work',
                'verbose_name_plural': 'schemes of work',
                'ordering': ('subject__name', 'school_class__name', '-version'),
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=48)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sequence', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('suggested_weeks', models.PositiveSmallIntegerField(default=1)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='curriculum.schemeofwork')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='schools.school')),
            ],
            options={
                'ordering': ('scheme', 'sequence', 'code'),
            },
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=48)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sequence', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='schools.school')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='curriculum.topic')),
            ],
            options={
                'ordering': ('topic', 'sequence', 'code'),
            },
        ),
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Stable Cambridge or school code.', max_length=48)),
                ('text', models.TextField()),
                ('sequence', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('version', models.PositiveIntegerField(default=1)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_objectives', to='schools.school')),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_objectives', to='curriculum.subtopic')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_objectives', to='curriculum.topic')),
            ],
            options={
                'ordering': ('topic', 'sequence', 'code'),
            },
        ),
        migrations.CreateModel(
            name='AssessmentObjective',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=48)),
                ('text', models.TextField()),
                ('sequence', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_objectives', to='schools.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_objectives', to='schools.subject')),
                ('learning_objectives', models.ManyToManyField(blank=True, related_name='assessment_objectives', to='curriculum.learningobjective')),
            ],
            options={
                'ordering': ('subject', 'sequence', 'code'),
                'indexes': [models.Index(fields=['school', 'subject', 'is_active'], name='curriculum__school__5d0d84_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'subject', 'code'), name='unique_subject_assessment_objective')],
            },
        ),
        migrations.AddIndex(
            model_name='schemeofwork',
            index=models.Index(fields=['school', 'subject', 'school_class', 'status'], name='curriculum__school__921bee_idx'),
        ),
        migrations.AddIndex(
            model_name='schemeofwork',
            index=models.Index(fields=['school', 'status', 'is_active'], name='curriculum__school__7cfbad_idx'),
        ),
        migrations.AddConstraint(
            model_name='schemeofwork',
            constraint=models.UniqueConstraint(fields=('school', 'code', 'version'), name='unique_school_scheme_code_version'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['school', 'scheme', 'sequence'], name='curriculum__school__9f5204_idx'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('scheme', 'code'), name='unique_scheme_topic_code'),
        ),
        migrations.AddIndex(
            model_name='subtopic',
            index=models.Index(fields=['school', 'topic', 'sequence'], name='curriculum__school__8a60e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='subtopic',
            constraint=models.UniqueConstraint(fields=('topic', 'code'), name='unique_topic_subtopic_code'),
        ),
        migrations.AddIndex(
            model_name='learningobjective',
            index=models.Index(fields=['school', 'topic', 'subtopic', 'is_active'], name='curriculum__school__8a4730_idx'),
        ),
        migrations.AddConstraint(
            model_name='learningobjective',
            constraint=models.UniqueConstraint(fields=('school', 'topic', 'code'), name='unique_topic_learning_objective_code'),
        ),
    ]
