# Generated by Django 5.2.17 on 2026-08-17 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumFramework',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('publisher', models.CharField(default='Cambridge International', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SchemeOfWork',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_code', models.CharField(max_length=32)),
                ('subject_name', models.CharField(max_length=120)),
                ('year_group', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('published_on', models.DateField(blank=True, null=True)),
                ('retired_on', models.DateField(blank=True, null=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schemes', to='curriculum.curriculumframework')),
            ],
            options={
                'ordering': ('framework__name', 'subject_name', 'year_group', '-version'),
            },
        ),
        migrations.CreateModel(
            name='AssessmentObjective',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_objectives', to='curriculum.schemeofwork')),
            ],
            options={
                'ordering': ('scheme', 'sequence', 'code'),
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=48)),
                ('title', models.CharField(max_length=200)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='curriculum.schemeofwork')),
            ],
            options={
                'ordering': ('scheme', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=48)),
                ('title', models.CharField(max_length=200)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='curriculum.topic')),
            ],
            options={
                'ordering': ('topic', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_objectives', to='curriculum.schemeofwork')),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_objectives', to='curriculum.subtopic')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_objectives', to='curriculum.topic')),
            ],
            options={
                'ordering': ('scheme', 'sequence', 'code'),
            },
        ),
        migrations.AddIndex(
            model_name='schemeofwork',
            index=models.Index(fields=['framework', 'subject_code', 'year_group', 'is_active'], name='curriculum__framewo_7d6a5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='schemeofwork',
            constraint=models.UniqueConstraint(fields=('framework', 'subject_code', 'year_group', 'version'), name='unique_global_scheme_version'),
        ),
        migrations.AddConstraint(
            model_name='schemeofwork',
            constraint=models.CheckConstraint(condition=models.Q(('retired_on__isnull', True), ('published_on__isnull', True), ('retired_on__gte', models.F('published_on')), _connector='OR'), name='scheme_retired_after_publication'),
        ),
        migrations.AddConstraint(
            model_name='assessmentobjective',
            constraint=models.UniqueConstraint(fields=('scheme', 'code'), name='unique_scheme_ao_code'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('scheme', 'sequence'), name='unique_scheme_topic_sequence'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('scheme', 'code'), name='unique_nonblank_scheme_topic_code'),
        ),
        migrations.AddConstraint(
            model_name='subtopic',
            constraint=models.UniqueConstraint(fields=('topic', 'sequence'), name='unique_topic_subtopic_sequence'),
        ),
        migrations.AddConstraint(
            model_name='subtopic',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('topic', 'code'), name='unique_nonblank_topic_subtopic_code'),
        ),
        migrations.AddConstraint(
            model_name='learningobjective',
            constraint=models.UniqueConstraint(fields=('scheme', 'code'), name='unique_scheme_lo_code'),
        ),
    ]
