# Generated by Django 5.2.17 on 2026-09-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemeofwork',
            name='syllabus_years',
            field=models.CharField(blank=True, default='2023-2027', help_text='e.g. 2023-2027', max_length=64),
        ),
    ]
