# Generated by Django 5.2.17 on 2026-08-16 18:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('planning', '0001_initial'),
        ('schools', '0002_calendarweek'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('returned', 'Returned'), ('resubmitted', 'Resubmitted'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('revision', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('resources', models.TextField(blank=True, help_text='WP-T02, page three resources area.')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_plans', to='schools.academicyear')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(help_text='Binds the plan to one teacher, subject and class.', on_delete=django.db.models.deletion.PROTECT, to='schools.teacherassignment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_plans', to='curriculum.schemeofwork')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('template_version', models.ForeignKey(help_text='The exact version this plan was authored against.', on_delete=django.db.models.deletion.PROTECT, to='planning.templateversion')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_plans', to='schools.term')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkPlanRow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_number', models.PositiveSmallIntegerField()),
                ('month_label', models.CharField(blank=True, max_length=40)),
                ('week_label', models.CharField(blank=True, max_length=80)),
                ('event_label', models.CharField(blank=True, max_length=120)),
                ('objective_labels', models.JSONField(blank=True, default=list)),
                ('remarks', models.TextField(blank=True, help_text='WP-T01, per week.')),
                ('calendar_week', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_plan_rows', to='schools.calendarweek')),
                ('learning_objectives', models.ManyToManyField(blank=True, related_name='work_plan_rows', to='curriculum.learningobjective')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='curriculum.subtopic')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='curriculum.topic')),
                ('work_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='plans.workplan')),
            ],
            options={
                'ordering': ('work_plan', 'week_number'),
            },
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('returned', 'Returned'), ('resubmitted', 'Resubmitted'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('revision', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('lesson_date', models.DateField(help_text='LP-S03, validated against term dates.')),
                ('objective_labels', models.JSONField(blank=True, default=list)),
                ('boys_present', models.PositiveIntegerField(blank=True, null=True)),
                ('girls_present', models.PositiveIntegerField(blank=True, null=True)),
                ('attendance_exception', models.CharField(blank=True, help_text='Audited reason when a count exceeds the roster (8.5).', max_length=255)),
                ('main_teaching_activity', models.TextField(blank=True)),
                ('assessment_ideas', models.TextField(blank=True)),
                ('notes_remarks', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(help_text='Binds the plan to one teacher, subject and class.', on_delete=django.db.models.deletion.PROTECT, to='schools.teacherassignment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('learning_objectives', models.ManyToManyField(blank=True, related_name='lesson_plans', to='curriculum.learningobjective')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='curriculum.subtopic')),
                ('template_version', models.ForeignKey(help_text='The exact version this plan was authored against.', on_delete=django.db.models.deletion.PROTECT, to='planning.templateversion')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='curriculum.topic')),
                ('work_plan_row', models.ForeignKey(blank=True, help_text='Set when the lesson was created from a Work Plan row.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to='plans.workplanrow')),
            ],
            options={
                'ordering': ('-lesson_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_type', models.CharField(max_length=20)),
                ('plan_id', models.UUIDField()),
                ('plan_revision', models.PositiveIntegerField(default=1)),
                ('plan_state', models.CharField(blank=True, max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('checksum', models.CharField(max_length=64)),
                ('byte_size', models.PositiveIntegerField(default=0)),
                ('verification_code', models.CharField(blank=True, max_length=12)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='planning.templateversion')),
            ],
            options={
                'ordering': ('-generated_at',),
                'indexes': [models.Index(fields=['school', 'plan_type', 'plan_id'], name='plans_gener_school__d900a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlanReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_type', models.CharField(max_length=20)),
                ('plan_id', models.UUIDField()),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('claimed', 'Started review'), ('returned', 'Returned'), ('resubmitted', 'Resubmitted'), ('approved', 'Approved'), ('archived', 'Archived')], max_length=20)),
                ('previous_state', models.CharField(max_length=20)),
                ('new_state', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['school', 'plan_type', 'plan_id'], name='plans_planr_school__21cfc7_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_id', models.CharField(help_text='Client-generated ID making replays idempotent.', max_length=64)),
                ('device_id', models.CharField(blank=True, max_length=64)),
                ('plan_type', models.CharField(blank=True, max_length=20)),
                ('plan_id', models.UUIDField(blank=True, null=True)),
                ('base_revision', models.PositiveIntegerField(blank=True, null=True)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('result', models.CharField(choices=[('applied', 'Applied'), ('duplicate', 'Duplicate'), ('conflict', 'Conflict'), ('rejected', 'Rejected')], max_length=20)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'operation_id'), name='unique_user_sync_operation')],
            },
        ),
        migrations.AddIndex(
            model_name='workplan',
            index=models.Index(fields=['school', 'state', 'author'], name='plans_workp_school__200bbf_idx'),
        ),
        migrations.AddConstraint(
            model_name='workplan',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'archived'), _negated=True), fields=('assignment', 'term'), name='one_active_work_plan_per_assignment_term'),
        ),
        migrations.AddConstraint(
            model_name='workplanrow',
            constraint=models.UniqueConstraint(fields=('work_plan', 'week_number'), name='unique_work_plan_week'),
        ),
        migrations.AddIndex(
            model_name='lessonplan',
            index=models.Index(fields=['school', 'state', 'author'], name='plans_lesso_school__d9e293_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonplan',
            index=models.Index(fields=['school', 'lesson_date'], name='plans_lesso_school__682c42_idx'),
        ),
    ]
