# Generated by Django 5.2.17 on 2026-08-17 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_type', models.CharField(choices=[('semester_work_plan', 'Semester Work Plan'), ('lesson_plan', 'Lesson Plan')], max_length=32)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_templates', to='schools.school')),
            ],
            options={
                'ordering': ('template_type', 'name'),
            },
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_id', models.CharField(max_length=48)),
                ('label', models.CharField(max_length=160)),
                ('field_class', models.CharField(choices=[('red', 'Teacher-entered'), ('blue', 'Controlled'), ('system', 'System-generated')], max_length=12)),
                ('control_type', models.CharField(choices=[('text', 'Single-line text'), ('textarea', 'Multi-line text'), ('select', 'Static picker'), ('date', 'Date'), ('number', 'Number'), ('boolean', 'Yes/no'), ('system', 'System-generated')], max_length=16)),
                ('is_required', models.BooleanField(default=False)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('page_number', models.PositiveSmallIntegerField(default=1)),
                ('x', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('y', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('help_text', models.TextField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_fields', to='schools.school')),
            ],
            options={
                'ordering': ('template_version', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='TemplateFieldOption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=120)),
                ('label', models.CharField(max_length=160)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='planning.templatefield')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_field_options', to='schools.school')),
            ],
            options={
                'ordering': ('field', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], default='draft', max_length=16)),
                ('source_asset', models.FileField(blank=True, upload_to='planning-template-masters/')),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('source_checksum', models.CharField(blank=True, max_length=64)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_versions', to='schools.school')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='planning.planningtemplate')),
            ],
            options={
                'ordering': ('template', '-version'),
            },
        ),
        migrations.AddField(
            model_name='templatefield',
            name='template_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='planning.templateversion'),
        ),
        migrations.AddConstraint(
            model_name='planningtemplate',
            constraint=models.UniqueConstraint(fields=('school', 'template_type', 'name'), name='unique_school_planning_template'),
        ),
        migrations.AddConstraint(
            model_name='templatefieldoption',
            constraint=models.UniqueConstraint(fields=('field', 'value'), name='unique_field_option_value'),
        ),
        migrations.AddConstraint(
            model_name='templatefieldoption',
            constraint=models.UniqueConstraint(fields=('field', 'sequence'), name='unique_field_option_sequence'),
        ),
        migrations.AddConstraint(
            model_name='templateversion',
            constraint=models.UniqueConstraint(fields=('template', 'version'), name='unique_template_version'),
        ),
        migrations.AddConstraint(
            model_name='templateversion',
            constraint=models.CheckConstraint(condition=models.Q(('effective_until__isnull', True), ('effective_from__isnull', True), ('effective_until__gte', models.F('effective_from')), _connector='OR'), name='template_version_valid_effective_dates'),
        ),
        migrations.AddConstraint(
            model_name='templatefield',
            constraint=models.UniqueConstraint(fields=('template_version', 'field_id'), name='unique_version_field_id'),
        ),
        migrations.AddConstraint(
            model_name='templatefield',
            constraint=models.UniqueConstraint(fields=('template_version', 'sequence'), name='unique_version_field_sequence'),
        ),
        migrations.AddConstraint(
            model_name='templatefield',
            constraint=models.CheckConstraint(condition=models.Q(('width__isnull', True), ('width__gt', 0), _connector='OR'), name='field_width_positive'),
        ),
        migrations.AddConstraint(
            model_name='templatefield',
            constraint=models.CheckConstraint(condition=models.Q(('height__isnull', True), ('height__gt', 0), _connector='OR'), name='field_height_positive'),
        ),
    ]
