# Generated by Django 5.2.17 on 2026-08-16 18:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_type', models.CharField(choices=[('work_plan', 'Semester Work Plan'), ('lesson_plan', 'Lesson Plan')], max_length=20)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_templates', to='schools.school')),
            ],
            options={
                'ordering': ('school', 'plan_type'),
            },
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_id', models.CharField(help_text='Stable register ID, for example LP-D01 or WP-T02.', max_length=16)),
                ('label', models.CharField(help_text='Printed label on the template.', max_length=160)),
                ('kind', models.CharField(choices=[('red', 'RED — controlled picker'), ('blue', 'BLUE — free text'), ('system', 'System — fixed or read-only')], max_length=10)),
                ('control', models.CharField(choices=[('cascading_select', 'Cascading searchable dropdown'), ('multi_select', 'Searchable multi-select'), ('select', 'Single select'), ('integer_picker', 'Bounded integer picker'), ('text', 'Single-line text'), ('textarea', 'Multi-line text'), ('date', 'Date'), ('computed', 'Computed read-only value'), ('static', 'Fixed template content')], max_length=24)),
                ('page', models.PositiveSmallIntegerField(default=1)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('is_required', models.BooleanField(default=False)),
                ('is_readonly', models.BooleanField(default=False)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('option_source', models.CharField(blank=True, help_text="Authorised source key, e.g. 'curriculum.subtopic' or 'roster.boys'.", max_length=64)),
                ('min_value', models.IntegerField(blank=True, null=True)),
                ('max_value', models.IntegerField(blank=True, null=True)),
                ('max_length', models.PositiveIntegerField(blank=True, null=True)),
                ('max_selections', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('box_x1', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('box_y1', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('box_x2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('box_y2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('overflow_policy', models.CharField(blank=True, help_text='Approved wrap/clip/continuation behaviour for this box.', max_length=24)),
                ('source_note', models.CharField(blank=True, max_length=255)),
                ('depends_on', models.ForeignKey(blank=True, help_text='Parent field in a cascading dependency.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='planning.templatefield')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_fields', to='schools.school')),
            ],
            options={
                'ordering': ('template_version', 'page', 'sequence', 'field_id'),
            },
        ),
        migrations.CreateModel(
            name='TemplateFieldOption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=120)),
                ('label', models.CharField(max_length=200)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='planning.templatefield')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_field_options', to='schools.school')),
            ],
            options={
                'ordering': ('field', 'sequence', 'label'),
            },
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('approved', 'Approved'), ('current', 'Current'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('page_count', models.PositiveSmallIntegerField(default=1)),
                ('page_width_pt', models.DecimalField(decimal_places=2, default=595.32, max_digits=8)),
                ('page_height_pt', models.DecimalField(decimal_places=2, default=841.92, max_digits=8)),
                ('annotation_source_name', models.CharField(blank=True, help_text='Annotated specification file, e.g. TEMPLATE.pdf.', max_length=255)),
                ('annotation_source_sha256', models.CharField(blank=True, max_length=64)),
                ('clean_master_name', models.CharField(blank=True, help_text='Unmarked production master used for rendering.', max_length=255)),
                ('clean_master_sha256', models.CharField(blank=True, max_length=64)),
                ('clean_master_approved', models.BooleanField(default=False, help_text='Set once the school supplies or approves an unmarked production master.')),
                ('notes', models.TextField(blank=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_template_versions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_versions', to='schools.school')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='planning.planningtemplate')),
            ],
            options={
                'ordering': ('template', '-version'),
            },
        ),
        migrations.AddField(
            model_name='templatefield',
            name='template_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='planning.templateversion'),
        ),
        migrations.AddConstraint(
            model_name='planningtemplate',
            constraint=models.UniqueConstraint(fields=('school', 'plan_type'), name='unique_school_planning_template'),
        ),
        migrations.AddConstraint(
            model_name='templatefieldoption',
            constraint=models.UniqueConstraint(fields=('field', 'value'), name='unique_field_option_value'),
        ),
        migrations.AddIndex(
            model_name='templateversion',
            index=models.Index(fields=['school', 'status'], name='planning_te_school__266bb9_idx'),
        ),
        migrations.AddConstraint(
            model_name='templateversion',
            constraint=models.UniqueConstraint(fields=('template', 'version'), name='unique_template_version_number'),
        ),
        migrations.AddConstraint(
            model_name='templateversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'current')), fields=('template',), name='one_current_version_per_template'),
        ),
        migrations.AddIndex(
            model_name='templatefield',
            index=models.Index(fields=['school', 'template_version', 'kind'], name='planning_te_school__30ca27_idx'),
        ),
        migrations.AddConstraint(
            model_name='templatefield',
            constraint=models.UniqueConstraint(fields=('template_version', 'field_id'), name='unique_version_field_id'),
        ),
    ]
