# Generated by Django 5.2.17 on 2026-08-17 10:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        ('planning', '0001_initial'),
        ('schools', '0002_calendarweek'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('returned', 'Returned'), ('resubmitted', 'Resubmitted'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('revision_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('resources', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_plans', to='schools.academicyear')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_plans', to='schools.teacherassignment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_plans', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_plans', to='curriculum.schemeofwork')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_plans', to='schools.school')),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_plans', to='planning.templateversion')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_plans', to='schools.term')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkPlanEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('returned', 'Returned'), ('resubmitted', 'Resubmitted'), ('approved', 'Approved'), ('archived', 'Archived')], max_length=20)),
                ('to_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('returned', 'Returned'), ('resubmitted', 'Resubmitted'), ('approved', 'Approved'), ('archived', 'Archived')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_plan_events', to='schools.school')),
                ('work_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='planning.workplan')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkPlanWeek',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('month_label', models.CharField(blank=True, max_length=32)),
                ('week_label', models.CharField(max_length=100)),
                ('event_label', models.CharField(blank=True, max_length=160)),
                ('is_instructional', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('calendar_week', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_plan_weeks', to='schools.calendarweek')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_plan_weeks', to='schools.school')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_plan_weeks', to='curriculum.topic')),
                ('work_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='planning.workplan')),
            ],
            options={
                'ordering': ('work_plan', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='WorkPlanWeekObjective',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_snapshot', models.CharField(max_length=64)),
                ('text_snapshot', models.TextField()),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_plan_selections', to='curriculum.learningobjective')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_plan_objectives', to='schools.school')),
                ('work_plan_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_selections', to='planning.workplanweek')),
            ],
            options={
                'ordering': ('work_plan_week', 'code_snapshot'),
            },
        ),
        migrations.AddIndex(
            model_name='workplan',
            index=models.Index(fields=['school', 'status', 'updated_at'], name='planning_wo_school__aa9941_idx'),
        ),
        migrations.AddConstraint(
            model_name='workplan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'archived'), _negated=True), fields=('assignment', 'term'), name='one_active_work_plan_per_assignment_term'),
        ),
        migrations.AddIndex(
            model_name='workplanevent',
            index=models.Index(fields=['school', 'work_plan', 'created_at'], name='planning_wo_school__25ab54_idx'),
        ),
        migrations.AddConstraint(
            model_name='workplanweek',
            constraint=models.UniqueConstraint(fields=('work_plan', 'sequence'), name='unique_work_plan_week'),
        ),
        migrations.AddConstraint(
            model_name='workplanweek',
            constraint=models.UniqueConstraint(fields=('work_plan', 'calendar_week'), name='unique_work_plan_calendar_week'),
        ),
        migrations.AddConstraint(
            model_name='workplanweekobjective',
            constraint=models.UniqueConstraint(fields=('work_plan_week', 'objective'), name='unique_week_learning_objective'),
        ),
    ]
