# Generated by Django 5.2.17 on 2026-08-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_workplan_workplanevent_workplanweek_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefield',
            name='field_class',
            field=models.CharField(choices=[('red', 'Controlled'), ('blue', 'Teacher-entered'), ('system', 'System-generated')], max_length=12),
        ),
    ]
