# Generated by Django 5.2.17 on 2026-08-17 11:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        ('planning', '0003_alter_templatefield_field_class'),
        ('schools', '0002_calendarweek'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lesson_date', models.DateField()),
                ('boys_attendance', models.PositiveSmallIntegerField()),
                ('girls_attendance', models.PositiveSmallIntegerField()),
                ('main_teaching_activity', models.TextField()),
                ('assessment_ideas', models.TextField()),
                ('notes_remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('returned', 'Returned'), ('resubmitted', 'Resubmitted'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('revision_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_plans', to='schools.academicyear')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_plans', to='schools.teacherassignment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_plans', to=settings.AUTH_USER_MODEL)),
                ('originating_work_plan_week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesson_plans', to='planning.workplanweek')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_plans', to='curriculum.schemeofwork')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='schools.school')),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesson_plans', to='curriculum.subtopic')),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_plans', to='planning.templateversion')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_plans', to='schools.term')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_plans', to='curriculum.topic')),
            ],
            options={
                'ordering': ('-lesson_date', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='LessonPlanEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('returned', 'Returned'), ('resubmitted', 'Resubmitted'), ('approved', 'Approved'), ('archived', 'Archived')], max_length=20)),
                ('to_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('returned', 'Returned'), ('resubmitted', 'Resubmitted'), ('approved', 'Approved'), ('archived', 'Archived')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='planning.lessonplan')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan_events', to='schools.school')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LessonPlanObjective',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_snapshot', models.CharField(max_length=64)),
                ('text_snapshot', models.TextField()),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_selections', to='planning.lessonplan')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_plan_selections', to='curriculum.learningobjective')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan_objectives', to='schools.school')),
            ],
            options={
                'ordering': ('lesson_plan', 'code_snapshot'),
            },
        ),
        migrations.AddIndex(
            model_name='lessonplan',
            index=models.Index(fields=['school', 'status', 'lesson_date'], name='planning_le_school__ceb6ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonplanobjective',
            constraint=models.UniqueConstraint(fields=('lesson_plan', 'objective'), name='unique_lesson_plan_objective'),
        ),
    ]
