# Generated by Django 5.2.14 on 2026-08-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_lessonplan_lessonplanevent_lessonplanobjective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='resources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
