# Generated by Django 5.2.14 on 2026-08-22 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        ('planning', '0005_lessonplan_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplanweek',
            name='lessons_per_week',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workplanweek',
            name='subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_plan_weeks', to='curriculum.subtopic'),
        ),
    ]
