# Generated by Django 5.2.14 on 2026-08-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_workplanweek_lessons_per_week_workplanweek_subtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplanweekobjective',
            name='is_met',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workplanweekobjective',
            name='met_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
