# Generated by Django 5.2.17 on 2026-09-02 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_workplanweekobjective_is_met_and_more'),
        ('schools', '0004_teachertimetable_teacherscheduleslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='schedule_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to='schools.teacherscheduleslot'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='boys_attendance',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='girls_attendance',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
