# Generated by Django 5.2.17 on 2026-09-03 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        ('planning', '0008_lessonplan_end_time_lessonplan_schedule_slot_and_more'),
        ('schools', '0004_teachertimetable_teacherscheduleslot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workplan',
            name='one_active_work_plan_per_assignment_term',
        ),
        migrations.AddField(
            model_name='workplan',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_plans', to='schools.schoolclass'),
        ),
        migrations.AddField(
            model_name='workplan',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_plans', to='schools.subject'),
        ),
        migrations.AlterField(
            model_name='lessonplanobjective',
            name='code_snapshot',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='lessonplanobjective',
            name='text_snapshot',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workplan',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_plans', to='schools.teacherassignment'),
        ),
        migrations.AddConstraint(
            model_name='workplan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'archived'), _negated=True), fields=('school', 'term', 'subject', 'school_class'), name='one_active_work_plan_per_subject_class_term'),
        ),
    ]
