# Generated by Django 5.2.17 on 2026-08-16 18:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarWeek',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveSmallIntegerField()),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('month_label', models.CharField(blank=True, max_length=40)),
                ('event_label', models.CharField(blank=True, help_text='Fixed calendar event, for example Revision Week.', max_length=120)),
                ('is_teaching_week', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_weeks', to='schools.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='schools.term')),
            ],
            options={
                'ordering': ('term', 'number'),
                'indexes': [models.Index(fields=['school', 'term', 'number'], name='schools_cal_school__067062_idx')],
                'constraints': [models.UniqueConstraint(fields=('term', 'number'), name='unique_term_week_number'), models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='week_ends_after_start')],
            },
        ),
    ]
