# Generated by Django 5.2.17 on 2026-08-17 10:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarWeek',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('month_label', models.CharField(blank=True, max_length=32)),
                ('event_label', models.CharField(blank=True, max_length=160)),
                ('is_instructional', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_weeks', to='schools.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_weeks', to='schools.term')),
            ],
            options={
                'ordering': ('term', 'sequence'),
                'indexes': [models.Index(fields=['school', 'term', 'sequence'], name='schools_cal_school__37e5fb_idx')],
                'constraints': [models.UniqueConstraint(fields=('term', 'sequence'), name='unique_term_calendar_week'), models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='calendar_week_valid_dates')],
            },
        ),
    ]
