# Generated by Django 5.2.17 on 2026-09-02 13:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_academicyear_unique_current'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherTimetable',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='schools/timetables/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('parsed_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('confirmed', 'Confirmed'), ('superseded', 'Superseded'), ('rejected', 'Rejected')], default='pending_review', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_timetables', to='schools.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_timetables', to='schools.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TeacherScheduleSlot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('period_label', models.CharField(blank=True, max_length=40)),
                ('room', models.CharField(blank=True, max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='schools.teacherassignment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='schools.school')),
                ('timetable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='schools.teachertimetable')),
            ],
            options={
                'ordering': ('day_of_week', 'start_time'),
            },
        ),
        migrations.AddIndex(
            model_name='teachertimetable',
            index=models.Index(fields=['school', 'teacher', 'status'], name='schools_tea_school__a2a596_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherscheduleslot',
            index=models.Index(fields=['school', 'assignment', 'day_of_week'], name='schools_tea_school__d4f6fe_idx'),
        ),
    ]
